
export const COUNTRY = [
    { value: 'ae', label: 'United Arab Emirates '},
    { value: 'bg', label: 'Bulgaria'},
    { value: 'br', label: 'Brazil'},
    { value: 'ca', label: 'Canada'},
    { value: 'cn', label: 'China'},
    { value: 'co', label: 'Colombia'},
    { value: 'cu', label: 'Cuba'},
    { value: 'do', label: 'Dominican Republic'},
    { value: 'eg', label: 'Egypt'},
    { value: 'fr', label: 'France'},
    { value: 'ie', label: 'Ireland'},
    { value: 'il', label: 'Israel'},
    { value: 'in', label: 'India'},
    { value: 'it', label: 'Italy'},
    { value: 'jp', label: 'Japan'},
    { value: 'kr', label: 'Korea (the Republic of)'},
    { value: 'ma', label: 'Morocco'},
    { value: 'mx', label: 'Mexico'},
    { value: 'no', label: 'Norway'},
    { value: 'nz', label: 'New Zealand'},
    { value: 'ph', label: 'Philippines'},
    { value: 'pl', label: 'Poland'},
    { value: 'ro', label: 'Romania'},
    { value: 'ru', label: 'Russian Federation'},
    { value: 'sa', label: 'Saudi Arabia'},
    { value: 'es', label: 'Spain'},
    { value: 'ua', label: 'Ukraine'},
    { value: 'us', label: 'United States'},
    { value: 'uk', label: 'United Kingdoms'},
]